{% set version = "2.9.0" %}

package:
  name: time-machine
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/t/time-machine/time-machine-{{ version }}.tar.gz
    sha256: 60222d43f6e93a926adc36ed37a54bc8e4d0d8d1c4d449096afcfe85086129c2
  - folder: src
    url: https://github.com/adamchainz/time-machine/archive/refs/tags/{{ version }}.tar.gz
    sha256: 4c356560a2af1b3235da6deeeb68de67afda2bcfbe2a810e211ae4c5df3684a4


build:
  skip: true  # [py<37]
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil

{% set cov_threshold = 98 %}  # [linux]
{% set cov_threshold = 59 %}  # [osx]
{% set cov_threshold = 0 %}  # [win]

test:
  source_files: src/tests
  imports:
    - time_machine
  commands:
    - pip check
    # can't test on windows due to use of ``time.tzset``
    - pytest src/tests -vv --cov=time_machine --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under={{ cov_threshold }}  # [unix]
  requires:
    - backports.zoneinfo
    - pip
    - pytest-cov
    - pytest-randomly
    - python-dateutil

about:
  home: https://github.com/adamchainz/time-machine
  summary: Travel through time in your tests.
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
