{% set version = "2.17.0" %}

# can't test on...
#  - (windows)/any (aarch64|ppcle64)/py<312 due to use of ``time.tzset``?
{% set can_test = osx or linux64 or (linux and py >= 312) %}

package:
  name: time-machine
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/t/time-machine/time_machine-{{ version }}.tar.gz
    sha256: bc31f23aa4c31b6567a7e5b2bbb0d1a0c0a1340c6d050c1f1b71cd0e2e76cb7f
  - folder: src
    url: https://github.com/adamchainz/time-machine/archive/refs/tags/{{ version }}.tar.gz
    sha256: 1cd8965cdd841a24d5f8e9c35a49c56f15a02e273186300360cfec621c0c5ef6

build:
  skip: true  # [py<39]
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - python-dateutil

test:
  source_files:
    - src/tests
  imports:
    - time_machine
  commands:
    - pip check
    {% if can_test %}
    - coverage run --source=time_machine --branch -m pytest src/tests -vv --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=98
    {% endif %}
  requires:
    - pip
    {% if can_test %}
    - backports.zoneinfo
    - coverage
    - pytest
    - pytest-randomly
    - python-dateutil
    {% endif %}

about:
  home: https://github.com/adamchainz/time-machine
  summary: Travel through time in your tests.
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
