# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.17.0
  # can't test on...
  #  - (windows)/any (aarch64|ppcle64)/py<312 due to use of ``time.tzset``?
  can_test: osx or linux64 or (linux and py >= 312)

package:
  name: time-machine
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/time-machine/time_machine-${{ version }}.tar.gz
    sha256: bc31f23aa4c31b6567a7e5b2bbb0d1a0c0a1340c6d050c1f1b71cd0e2e76cb7f
    target_directory: dist
  - url: https://github.com/adamchainz/time-machine/archive/refs/tags/${{ version }}.tar.gz
    sha256: 1cd8965cdd841a24d5f8e9c35a49c56f15a02e273186300360cfec621c0c5ef6
    target_directory: src

build:
  number: 0
  script: cd dist && ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - python-dateutil

tests:
  - python:
      imports: time_machine
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - pip
        - backports.zoneinfo
        - coverage
        - pytest
        - pytest-randomly
        - python-dateutil
        - tokenize-rt
    script:
      - pip check
      - coverage run --source=time_machine --branch -m pytest src/tests -vv --color=yes --tb=long
      - coverage report --show-missing --skip-covered --fail-under=98

about:
  summary: Travel through time in your tests.
  license: MIT
  license_file: dist/LICENSE
  homepage: https://github.com/adamchainz/time-machine

extra:
  recipe-maintainers:
    - bollwyvl
