# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.1.0"

package:
  name: time-machine
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/time-machine/time_machine-${{ version }}.tar.gz
    sha256: 90831c2cf9e18e4199abb85fafa0c0ca0c6c15d0894a03ef68d5005a796c4f27
    target_directory: dist
  - url: https://github.com/adamchainz/time-machine/archive/refs/tags/${{ version }}.tar.gz
    sha256: 5ccc9add7f678a2652249d12efea446db0540acc90240ae9327d2fdcbba4f920
    target_directory: src

build:
  number: 0
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
  run_constraints:
    - python-dateutil >=2.8.2

tests:
  - python:
      imports: time_machine
      pip_check: true
  - if: osx or linux64 or (linux and match(python, ">=3.12"))
    then:
      files:
        source:
          - src/tests/
      requirements:
        run:
          - backports.zoneinfo
          - coverage
          - pytest
          - pytest-randomly
          - python-dateutil
          - tokenize-rt
      script:
        - coverage run --source=time_machine --branch -m pytest src/tests -vv --color=yes --tb=long -p pytester
        - coverage report --show-missing --skip-covered --fail-under=98

about:
  summary: Travel through time in your tests.
  license: MIT
  license_file: dist/LICENSE
  homepage: https://github.com/adamchainz/time-machine

extra:
  recipe-maintainers:
    - bollwyvl
