bot:
  inspection: hint-all
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
# can't use on ppc64le
# conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native_and_emulated
